language: csharp
mono: none
dotnet: 6.0.300

script:
  - ./build.sh

addons:
  apt:
    packages:
      - imagemagick
      - pngquant
      - optipng

deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
